name: Backend CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./backend

    steps:
    - uses: actions/checkout@v4
    - name: Check
      run: cargo check --all-features
    - name: Run tests
      run: cargo test --all-features
    - name: Check Formatting
      run: cargo fmt --all -- --check 
    - name: 
      run: | 
        cargo install cargo-audit --locked
        cargo audit

