name: Frontend CI - React

on:
  push:
    branches: [ "main" ]
    paths:
      - 'frontend/**'
      - '.github/workflows/ci_frontend.yml'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'frontend/**'

defaults:
  run:
    working-directory: ./frontend

jobs:
  quality-gate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '24'
          cache: 'npm'
          # tell the cache where the lockfile lives
          cache-dependency-path: './frontend/package-lock.json'

      - name: Install dependencies
        run: npm ci

      - name: Run Linter
        run: npm run lint

      - name: Run Tests
        run: npm run test

      - name: Build Application
        run: npm run build
